export default [
  { value: '1', label: 'Russia' },
  { value: '2', label: 'USA' },
  { value: '3', label: 'UK' },
  { value: '4', label: 'Australia' },
  { value: '5', label: 'Hungary' },
  { value: '6', label: 'Canada' },
  { value: '7', label: 'Belarus' },
  { value: '8', label: 'Germany' },
  { value: '9', label: 'France' },
  { value: '10', label: 'Italy' },
  { value: '11', label: 'Spain' },
  { value: '12', label: 'Poland' },
  { value: '13', label: 'Netherlands' },
  { value: '14', label: 'Belgium' },
  { value: '15', label: 'Switzerland' },
  { value: '16', label: 'Austria' },
  { value: '17', label: 'Sweden' },
  { value: '18', label: 'Norway' },
  { value: '19', label: 'Denmark' },
  { value: '20', label: 'Finland' },
  { value: '21', label: 'Portugal' },
  { value: '22', label: 'Greece' },
  { value: '23', label: 'Ireland' },
  { value: '24', label: 'New Zealand' },
  { value: '25', label: 'Japan' },
  { value: '26', label: 'South Korea' },
  { value: '27', label: 'China' },
  { value: '28', label: 'India' },
  { value: '29', label: 'Brazil' },
  { value: '30', label: 'Argentina' },
  { value: '31', label: 'Chile' },
  { value: '32', label: 'Mexico' },
  { value: '33', label: 'Colombia' },
  { value: '34', label: 'Peru' },
  { value: '35', label: 'Venezuela' },
  { value: '36', label: 'Ecuador' },
  { value: '37', label: 'Bolivia' },
  { value: '38', label: 'Paraguay' },
  { value: '39', label: 'Uruguay' },
  { value: '40', label: 'Costa Rica' },
  { value: '41', label: 'Panama' },
  { value: '42', label: 'Cuba' },
  { value: '43', label: 'Dominican Republic' },
  { value: '44', label: 'Haiti' },
  { value: '45', label: 'Jamaica' },
  { value: '46', label: 'Trinidad and Tobago' },
  { value: '47', label: 'Barbados' },
  { value: '48', label: 'Antigua and Barbuda' },
  { value: '49', label: 'Saint Lucia' },
  { value: '50', label: 'Grenada' },
  { value: '51', label: 'Bahamas' },
  { value: '52', label: 'Belize' },
  { value: '53', label: 'Guatemala' },
  { value: '54', label: 'Honduras' },
  { value: '55', label: 'El Salvador' },
  { value: '56', label: 'Nicaragua' },
  { value: '57', label: 'Costa Rica' },
  { value: '58', label: 'Panama' },
  { value: '59', label: 'Cuba' },
  { value: '60', label: 'Dominican Republic' },
  { value: '61', label: 'Haiti' },
  { value: '62', label: 'Jamaica' },
  { value: '63', label: 'Trinidad and Tobago' },
  { value: '64', label: 'Barbados' },
  { value: '65', label: 'Antigua and Barbuda' },
  { value: '66', label: 'Saint Lucia' },
  { value: '67', label: 'Grenada' },
  { value: '68', label: 'Bahamas' },
  { value: '69', label: 'Belize' },
  { value: '70', label: 'Guatemala' },
  { value: '71', label: 'Honduras' },
  { value: '72', label: 'El Salvador' },
  { value: '73', label: 'Nicaragua' },
  { value: '74', label: 'Costa Rica' },
  { value: '75', label: 'Panama' },
  { value: '76', label: 'Cuba' },
  { value: '77', label: 'Dominican Republic' },
  { value: '78', label: 'Haiti' },
  { value: '79', label: 'Jamaica' },
  { value: '80', label: 'Trinidad and Tobago' },
  { value: '81', label: 'Barbados' },
  { value: '82', label: 'Antigua and Barbuda' },
  { value: '83', label: 'Saint Lucia' },
  { value: '84', label: 'Grenada' },
  { value: '85', label: 'Bahamas' },
  { value: '86', label: 'Belize' },
  { value: '87', label: 'Guatemala' },
  { value: '88', label: 'Honduras' },
  { value: '89', label: 'El Salvador' },
  { value: '90', label: 'Nicaragua' },
  { value: '91', label: 'Costa Rica' },
  { value: '92', label: 'Panama' },
  { value: '93', label: 'Cuba' },
  { value: '94', label: 'Dominican Republic' },
  { value: '95', label: 'Haiti' },
  { value: '96', label: 'Jamaica' },
  { value: '97', label: 'Trinidad and Tobago' },
  { value: '98', label: 'Barbados' },
  { value: '99', label: 'Antigua and Barbuda' },
  { value: '100', label: 'Saint Lucia' },
  { value: '101', label: 'Grenada' },
  { value: '102', label: 'Bahamas' },
  { value: '103', label: 'Belize' },
  { value: '104', label: 'Guatemala' },
  { value: '105', label: 'Honduras' },
  { value: '106', label: 'El Salvador' },
  { value: '107', label: 'Nicaragua' },
  { value: '108', label: 'Costa Rica' },
  { value: '109', label: 'Panama' },
  { value: '110', label: 'Cuba' },
  { value: '111', label: 'Dominican Republic' },
  { value: '112', label: 'Haiti' },
  { value: '113', label: 'Jamaica' },
  { value: '114', label: 'Trinidad and Tobago' },
  { value: '115', label: 'Barbados' },
  { value: '116', label: 'Antigua and Barbuda' },
  { value: '117', label: 'Saint Lucia' },
  { value: '118', label: 'Grenada' },
  { value: '119', label: 'Bahamas' },
  { value: '120', label: 'Belize' },
  { value: '121', label: 'Guatemala' },
  { value: '122', label: 'Honduras' },
  { value: '123', label: 'El Salvador' },
  { value: '124', label: 'Nicaragua' },
  { value: '125', label: 'Costa Rica' },
  { value: '126', label: 'Panama' },
  { value: '127', label: 'Cuba' },
  { value: '128', label: 'Dominican Republic' },
  { value: '129', label: 'Haiti' },
  { value: '130', label: 'Jamaica' },
  { value: '131', label: 'Trinidad and Tobago' },
  { value: '132', label: 'Barbados' },
  { value: '133', label: 'Antigua and Barbuda' },
  { value: '134', label: 'Saint Lucia' },
  { value: '135', label: 'Grenada' },
  { value: '136', label: 'Bahamas' },
  { value: '137', label: 'Belize' },
  { value: '138', label: 'Guatemala' },
  { value: '139', label: 'Honduras' },
  { value: '140', label: 'El Salvador' },
  { value: '141', label: 'Nicaragua' },
  { value: '142', label: 'Costa Rica' },
  { value: '143', label: 'Panama' },
  { value: '144', label: 'Cuba' },
  { value: '145', label: 'Dominican Republic' },
  { value: '146', label: 'Haiti' },
  { value: '147', label: 'Jamaica' },
  { value: '148', label: 'Trinidad and Tobago' },
  { value: '149', label: 'Barbados' },
  { value: '150', label: 'Antigua and Barbuda' },
]
