export default [
  { value: '1', label: 'Harry Potter' },
  { value: '2', label: 'Ron Weasley' },
  { value: '3', label: 'Hermione Granger' },
  { value: '4', label: 'Albus Dumbledore' },
  { value: '5', label: 'Severus Snape' },
  { value: '6', label: 'Lord Voldemort' },
  { value: '7', label: 'Draco Malfoy' },
  { value: '8', label: 'Frodo Baggins' },
  { value: '9', label: 'Samwise Gamgee' },
  { value: '10', label: 'Aragorn' },
  { value: '11', label: 'Gandalf' },
  { value: '12', label: 'Legolas' },
  { value: '13', label: 'Gimli' },
  { value: '14', label: 'Sauron' },
  { value: '15', label: 'Galadriel' },
  { value: '16', label: 'Geralt of Rivia' },
  { value: '17', label: 'Yennefer of Vengerberg' },
  { value: '18', label: 'Ciri' },
  { value: '19', label: 'Triss Merigold' },
  { value: '20', label: 'Dandelion' },
  { value: '21', label: 'Vesemir' },
  { value: '22', label: 'Louis XIV' },
  { value: '23', label: 'Napoleon Bonaparte' },
  { value: '24', label: 'Pierre Bezukhov' },
  { value: '25', label: 'Natasha Rostova' },
  { value: '26', label: 'Andrei Bolkonsky' },
  { value: '27', label: 'Ilya Oblomov' },
  { value: '28', label: 'Olga Ivanovna' },
  { value: '29', label: 'Ivan Goncharov' },
  { value: '30', label: 'Miguel de Cervantes' },
  { value: '31', label: 'Don Quixote' },
  { value: '32', label: 'Sancho Panza' },
  { value: '33', label: 'William Shakespeare' },
  { value: '34', label: 'Hamlet' },
  { value: '35', label: 'Romeo Montague' },
  { value: '36', label: 'Juliet Capulet' },
  { value: '37', label: 'Elizabeth Bennet' },
  { value: '38', label: 'Mr. Darcy' },
  { value: '39', label: 'Jane Austen' },
  { value: '40', label: 'Hercule Poirot' },
  { value: '41', label: 'Miss Marple' },
  { value: '42', label: 'Agatha Christie' },
  { value: '43', label: 'Sherlock Holmes' },
  { value: '44', label: 'Dr. Watson' },
  { value: '45', label: 'Arthur Conan Doyle' },
  { value: '46', label: 'Tom Sawyer' },
  { value: '47', label: 'Huckleberry Finn' },
  { value: '48', label: 'Mark Twain' },
  { value: '49', label: 'Jane Eyre' },
  { value: '50', label: 'Mr. Rochester' },
  { value: '51', label: 'Charlotte Bronte' },
  { value: '52', label: 'Holden Caulfield' },
  { value: '53', label: 'J.D. Salinger' },
  { value: '54', label: 'Fyodor Dostoevsky' },
  { value: '55', label: 'Raskolnikov' },
  { value: '56', label: 'Alyosha Karamazov' },
  { value: '57', label: 'Fyodor Karamazov' },
  { value: '58', label: 'Charles Dickens' },
  { value: '59', label: 'Oliver Twist' },
  { value: '60', label: 'David Copperfield' },
  { value: '61', label: 'Edmond Dantès' },
  { value: '62', label: 'Alexandre Dumas' },
  { value: '63', label: 'Molly Bloom' },
  { value: '64', label: 'Leopold Bloom' },
  { value: '65', label: 'James Joyce' },
  { value: '66', label: 'Stephen Dedalus' },
  { value: '67', label: 'Marilyn Monroe' },
  { value: '68', label: 'Arthur Miller' },
  { value: '69', label: 'John F. Kennedy' },
  { value: '70', label: 'Martin Luther King Jr.' },
  { value: '71', label: 'Abraham Lincoln' },
  { value: '72', label: 'George Washington' },
  { value: '73', label: 'Thomas Jefferson' },
  { value: '74', label: 'Benjamin Franklin' },
  { value: '75', label: 'Winston Churchill' },
  { value: '76', label: 'Franklin D. Roosevelt' },
  { value: '77', label: 'Mahatma Gandhi' },
  { value: '78', label: 'Nelson Mandela' },
  { value: '79', label: 'Albert Einstein' },
  { value: '80', label: 'Isaac Newton' },
  { value: '81', label: 'Galileo Galilei' },
  { value: '82', label: 'Nikola Tesla' },
  { value: '83', label: 'Thomas Edison' },
  { value: '84', label: 'Marie Curie' },
  { value: '85', label: 'Stephen Hawking' },
  { value: '86', label: 'Charles Darwin' },
  { value: '87', label: 'Leonardo da Vinci' },
  { value: '88', label: 'Michelangelo' },
  { value: '89', label: 'Pablo Picasso' },
  { value: '90', label: 'Vincent van Gogh' },
  { value: '91', label: 'Claude Monet' },
  { value: '92', label: 'Rembrandt' },
  { value: '93', label: 'Salvador Dali' },
  { value: '94', label: 'Edvard Munch' },
  { value: '95', label: 'Johannes Vermeer' },
  { value: '96', label: 'Frida Kahlo' },
  { value: '97', label: 'Andy Warhol' },
  { value: '98', label: 'Banksy' },
  { value: '99', label: 'Wolfgang Amadeus Mozart' },
  { value: '100', label: 'Ludwig van Beethoven' },
  { value: '101', label: 'Johann Sebastian Bach' },
  { value: '102', label: 'Frederic Chopin' },
  { value: '103', label: 'Pyotr Ilyich Tchaikovsky' },
  { value: '104', label: 'Igor Stravinsky' },
  { value: '105', label: 'Antonio Vivaldi' },
  { value: '106', label: 'George Frideric Handel' },
  { value: '107', label: 'Giuseppe Verdi' },
  { value: '108', label: 'Richard Wagner' },
  { value: '109', label: 'Johannes Brahms' },
  { value: '110', label: 'Franz Schubert' },
  { value: '111', label: 'Robert Schumann' },
  { value: '112', label: 'Claude Debussy' },
  { value: '113', label: 'Maurice Ravel' },
  { value: '114', label: 'Sergei Rachmaninoff' },
  { value: '115', label: 'Dmitri Shostakovich' },
  { value: '116', label: 'Aram Khachaturian' },
  { value: '117', label: 'Edgar Allan Poe' },
  { value: '118', label: 'H.P. Lovecraft' },
  { value: '119', label: 'Stephen King' },
  { value: '120', label: 'J.R.R. Tolkien' },
  { value: '121', label: 'C.S. Lewis' },
  { value: '122', label: 'George R.R. Martin' },
  { value: '123', label: 'J.K. Rowling' },
  { value: '124', label: 'Neil Gaiman' },
  { value: '125', label: 'Terry Pratchett' },
  { value: '126', label: 'Ray Bradbury' },
  { value: '127', label: 'Isaac Asimov' },
  { value: '128', label: 'Arthur C. Clarke' },
  { value: '129', label: 'Philip K. Dick' },
  { value: '130', label: 'Ursula K. Le Guin' },
  { value: '131', label: 'Octavia E. Butler' },
  { value: '132', label: 'Margaret Atwood' },
  { value: '133', label: 'Virginia Woolf' },
  { value: '134', label: 'James Baldwin' },
  { value: '135', label: 'Toni Morrison' },
  { value: '136', label: 'Harper Lee' },
  { value: '137', label: 'F. Scott Fitzgerald' },
  { value: '138', label: 'Ernest Hemingway' },
  { value: '139', label: 'John Steinbeck' },
  { value: '140', label: 'Mark Z. Danielewski' },
  { value: '141', label: 'Gabriel Garcia Marquez' },
  { value: '142', label: 'Mario Vargas Llosa' },
  { value: '143', label: 'Isabel Allende' },
  { value: '144', label: 'Paulo Coelho' },
  { value: '145', label: 'Milan Kundera' },
  { value: '146', label: 'Albert Camus' },
  { value: '147', label: 'Jean-Paul Sartre' },
  { value: '148', label: 'Simone de Beauvoir' },
  { value: '149', label: 'Franz Kafka' },
  { value: '150', label: 'Leo Tolstoy' },
  { value: '151', label: 'Anton Chekhov' },
  { value: '152', label: 'Boris Pasternak' },
  { value: '153', label: 'Vladimir Nabokov' },
  { value: '154', label: 'Alexander Pushkin' },
  { value: '155', label: 'Mikhail Bulgakov' },
  { value: '156', label: 'Nikolai Gogol' },
  { value: '157', label: 'Thomas Mann' },
  { value: '158', label: 'Hermann Hesse' },
  { value: '159', label: 'Gustav Flaubert' },
  { value: '160', label: 'Marcel Proust' },
  { value: '161', label: 'Honore de Balzac' },
  { value: '162', label: 'Victor Hugo' },
  { value: '163', label: 'Albert Camus' },
  { value: '164', label: 'Jean-Paul Sartre' },
  { value: '165', label: 'Simone de Beauvoir' },
  { value: '166', label: 'Franz Kafka' },
  { value: '167', label: 'Leo Tolstoy' },
  { value: '168', label: 'Anton Chekhov' },
  { value: '169', label: 'Boris Pasternak' },
  { value: '170', label: 'Vladimir Nabokov' },
  { value: '171', label: 'Alexander Pushkin' },
  { value: '172', label: 'Mikhail Bulgakov' },
  { value: '173', label: 'Nikolai Gogol' },
  { value: '174', label: 'Thomas Mann' },
  { value: '175', label: 'Hermann Hesse' },
  { value: '176', label: 'Gustav Flaubert' },
  { value: '177', label: 'Marcel Proust' },
  { value: '178', label: 'Honore de Balzac' },
  { value: '179', label: 'Victor Hugo' },
  { value: '180', label: 'Albert Camus' },
  { value: '181', label: 'Jean-Paul Sartre' },
  { value: '182', label: 'Simone de Beauvoir' },
  { value: '183', label: 'Franz Kafka' },
  { value: '184', label: 'Leo Tolstoy' },
  { value: '185', label: 'Anton Chekhov' },
  { value: '186', label: 'Boris Pasternak' },
  { value: '187', label: 'Vladimir Nabokov' },
  { value: '188', label: 'Alexander Pushkin' },
  { value: '189', label: 'Mikhail Bulgakov' },
  { value: '190', label: 'Nikolai Gogol' },
  { value: '191', label: 'Thomas Mann' },
  { value: '192', label: 'Hermann Hesse' },
  { value: '193', label: 'Gustav Flaubert' },
  { value: '194', label: 'Marcel Proust' },
  { value: '195', label: 'Honore de Balzac' },
  { value: '196', label: 'Victor Hugo' },
  { value: '197', label: 'Albert Camus' },
  { value: '198', label: 'Jean-Paul Sartre' },
  { value: '199', label: 'Simone de Beauvoir' },
  { value: '200', label: 'Franz Kafka' },
]
